server:
  port: 8081

aws:
  dynamodb:
    region: us-east-1
    table-name: TaskTable

spring:
  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="WU4SCPDTQCS5AUWK"
        password="cflt+TpucklOCj4wM5v2bxUd6VpGcWW2KT2WAjh7wtdFkGXUsLE2dDkX4nVnav3A";
    consumer:
      group-id: task-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record
